containers:
  build-env:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - local: .
        container: /code
        options: cached
      - type: cache
        name: nuget-cache
        container: /root/.nuget/packages
      - type: cache
        name: weatherApi-obj
        container: /code/src/WeatherApi/obj
      - type: cache
        name: weatherApi-tests-obj
        container: /code/src/WeatherApi.Tests/obj
    working_directory: /code
