steps:
 
# Run Tests
  

- name: "gcr.io/cloud-builders/dotnet"
  entrypoint: 'bash'
  args:[
    - '-c'
    - |
          dotnet test --no-build -c 'eshoponweb-37264/WeatherApi.Tests'
          ]
 #End Tests
# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
         'gcr.io/eshoponweb-37264/dotnetprod/myimage:$SHORT_SHA', '.']
  # [END cloudbuild_python_image_yaml]
  